# Generated by Django 4.2.17 on 2024-12-12 06:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Name of the file', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Metadata in JSON format', null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Geometry of the spatial data', null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
